kind: pipeline
type: docker
name: default

steps:
- name: publish frontend
  image: plugins/docker
  settings:
    dockerfile: Dockerfile
    repo: mauriceo/mandelbrot
    tags:
      - "1.0"
      - latest
    username: 
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    branch:
      - master
    event:
      - push

- name: send telegram notification
  image: appleboy/drone-telegram
  settings:
    token: 
      from_secret: tg_bot_token
    to: -1001411660806